title: WIT IEEE Nugget Industries Documentation
logo: ./assets/img/logo.png
description: >
  This is the documentation for the Nugget Industries team. 
url: https://wit-ieee-nugget-industries-2019.github.io/
repository: https://github.com/WIT-IEEE-Nugget-Industries-2019/WIT-IEEE-Nugget-Industries-2019.github.io
twitter:
  username: 
theme: jekyll-theme-minimal
plugins:
- jekyll-avatar
- jekyll-sitemap
- jemoji
